name = "workers-cloudflare-com"
type = "webpack"
account_id = "8995c0f49cdcf57eb54d2c1e52b7d2f3"
workers_dev = true
kv-namespaces = [
  { binding = "BUILT_WITH_WORKERS", id = "b2817b8f747d4f1b9bf87712eb72d1b5" } # prod
]

[env.production]
workers_dev = false
route = "workers.cloudflare.com/*"
zone_id = "29ed9c83c2c78d6967876c4053ec8154"
kv-namespaces = [
  { binding = "BUILT_WITH_WORKERS", id = "b2817b8f747d4f1b9bf87712eb72d1b5" } # prod
]

[site]
bucket = "./public"
entry-point = "workers-site"
