on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@master
    - name: Add NPM token
      run: "echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > ~/.npmrc"
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: NPM install
      run: "npm install"
    - name: Build app
      run: "npm run build"
      env:
        SANITY_READ_TOKEN: ${{ secrets.SANITY_READ_TOKEN }}
